### ISSUE TITLE
colorama dependency?

### ISSUE THREAD

**Issue by cabo** [mnot/ietf-comments#9]
I had to install colorama manually (pip install) to make ietf-comments work.

**Comment by mnot** [comment]
What version are you running? `ietf-comments -v`.

**Comment by cabo** [comment]
``` 
$ ietf-comments -v
0.0.4
``` 

Install log was:

```
$ pip install ietf-comments
Collecting ietf-comments
  Downloading ietf_comments-0.0.4-py3-none-any.whl (7.0 kB)
Collecting commonmark
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
[...]
Installing collected packages: commonmark, ietf-comments
[...]
Successfully installed commonmark-0.9.1 ietf-comments-0.0.4
...
```

**Comment by cabo** [comment]
Yeah, I didn't read the part about Python 3.10.

**Comment by mnot** [comment]
:)

I just pushed 0.2.2, which drops the Python requirement to 3.6 but errors if you use a feature that requires 3.10 (currently, just `rfced-comments`. 

Unfortunately, pip will install the latest version of a package that supports the version of Python that you're using -- even if it's very old, and silently. I've opened a bug over there, but they don't seem likely to address it anytime soon.

**Comment by cabo** [comment]
Thank you for the update.  Now I get:

```
$ ietf-comments -g core-wg/core-problem-details AD\ Review\ of\ draft-ietf-core-problem-details-04.eml -a
Traceback (most recent call last):
  File "/Users/cabo/bin/ietf-comments", line 5, in <module>
    from ietf_comments.ui import ietf_comments_cli
  File "/Users/cabo/lib/python3.9/site-packages/ietf_comments/ui.py", line 6, in <module>
    from .xml_comments import parse_xml_comments
  File "/Users/cabo/lib/python3.9/site-packages/ietf_comments/xml_comments.py", line 21, in <module>
    class XmlCommentHandler(xml.sax.handler.LexicalHandler):
AttributeError: module 'xml.sax.handler' has no attribute 'LexicalHandler'
```

**Comment by mnot** [comment]
Ah. Try 0.2.3.

Thanks.

**Comment by cabo** [comment]
I'm not lucky today.

```
$ ietf-comments -g core-wg/core-problem-details AD\ Review\ of\ draft-ietf-core-problem-details-04.eml
Traceback (most recent call last):
  File "/Users/cabo/bin/ietf-comments", line 8, in <module>
    sys.exit(ietf_comments_cli())
  File "/Users/cabo/lib/python3.9/site-packages/ietf_comments/ui.py", line 82, in ietf_comments_cli
    comments = parse_markdown_comments(args.comment_file, cli)
  File "/Users/cabo/lib/python3.9/site-packages/ietf_comments/md_comments.py", line 162, in parse_markdown_comments
    renderer.render(doc)
  File "/Users/cabo/lib/python3.9/site-packages/commonmark/render/renderer.py", line 19, in render
    getattr(self, type_)(event['node'], event['entering'])
  File "/Users/cabo/lib/python3.9/site-packages/ietf_comments/md_comments.py", line 81, in block_quote
    change_location = self.changes.find_change_line(content)
  File "/Users/cabo/lib/python3.9/site-packages/ietf_comments/changes.py", line 33, in find_change_line
    if old_words[0] in line_words or words_consumed > 0:
IndexError: list index out of range
$ ietf-comments -v
0.2.3
```

Input copy-pasted from <https://mailarchive.ietf.org/arch/msg/core/UnvM0Am3w4w2sU85i1PaTRBMvdc>

**Comment by mnot** [comment]
Try 0.2.4.

Is there one or more lines with just `>` on them, surrounded by blank lines, by any chance?

**Comment by cabo** [comment]
Input was: <https://mailarchive.ietf.org/arch/msg/core/UnvM0Am3w4w2sU85i1PaTRBMvdc>
There are > lines, but with a "Section nnn" right before them (no blank lines).

0.2.4: looks much better now:

``` 
$ ietf-comments -g core-wg/core-problem-details AD\ Review\ of\ draft-ietf-core-problem-details-04.txt -a
Warning: Unrecognised h2 section notes.
Document: draft-ietf-core-problem-details
Revision: 04
CC: @fpalombini
```

(Now I need to find out why authentication fails.)
